# IFS-specific retargeting of the px4-dev-ros-noetic Dockerfile

FROM px4io/px4-dev-simulation-focal:latest

ENV ROS_DISTRO noetic

# setup ros keys
RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list' \
	&& sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list' \
	&& sh -c 'echo "deb http://packages.ros.org/ros-shadow-fixed/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-shadow.list' \
	&& apt-get update \
	&& apt-get -y --quiet --no-install-recommends install \
		build-essential \
		geographiclib-tools \
		libeigen3-dev \
		libgeographic-dev \
		libopencv-dev \
		libyaml-cpp-dev \
		python3-catkin-tools \
		python3-catkin-lint \
		python3-rosdep \
		python3-rosinstall \
		python3-rosinstall-generator \
		python3-wstool \
		ros-$ROS_DISTRO-gazebo-ros-pkgs \
		ros-$ROS_DISTRO-geodesy \
		ros-$ROS_DISTRO-hector-gazebo-plugins \
		ros-$ROS_DISTRO-image-geometry \
		ros-$ROS_DISTRO-libg2o \
		ros-$ROS_DISTRO-mavlink \
		ros-$ROS_DISTRO-mavros \
		ros-$ROS_DISTRO-mavros-extras \
		ros-$ROS_DISTRO-mavros-msgs \
		ros-$ROS_DISTRO-move-base-msgs \
		ros-$ROS_DISTRO-nmea-msgs \
		ros-$ROS_DISTRO-octomap \
		ros-$ROS_DISTRO-octomap-ros \
		ros-$ROS_DISTRO-octomap-msgs \
		ros-$ROS_DISTRO-octomap-rviz-plugins \
		ros-$ROS_DISTRO-pcl-conversions \
		ros-$ROS_DISTRO-pcl-msgs \
		ros-$ROS_DISTRO-pcl-ros \
		ros-$ROS_DISTRO-desktop \
		ros-$ROS_DISTRO-rostest \
		ros-$ROS_DISTRO-rosunit \
		xmlstarlet \
		xvfb \
	&& geographiclib-get-geoids egm96-5 \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Clone the px4tools repository and install Python packages
RUN git clone https://github.com/dronecrew/px4tools.git /tmp/px4tools && \
    pip3 install -U \
		jupyter \
    	/tmp/px4tools \
    	pymavlink \
    	osrf-pycommon && \
    rm -rf /tmp/px4tools

# bootstrap rosdep
RUN rosdep init && rosdep update

# build as
# docker build -t vividlibra/px4-dev-ros-noetic-desktop -f Dockerfile_ros-noetic-desktop .
